### ISSUE TITLE
Requirement bump for dependancies

### ISSUE THREAD

**Issue by tardinha** [symbiote/silverstripe-elemental-listingpagelisting#2] opened 2019-03-18 04:35 UTC
Hi,

Could the requirements for elemental be relaxed a bit to allow version 3 to be installed?

Cheers

Mark

**Comment by nglasl** [comment] 2019-03-18 05:06
Hey @tardinha, I don't see any issues with this but it'll need some testing to confirm there's no issues. To get around this for now, what you can do is define elemental in your composer requirements like `3.0.0 as 2.0`.

**Comment by tardinha** [comment] 2019-03-18 05:09
@nglasl, yep, that's what I do now :)

I can confirm this module works correctly with elemental 2, 3 and 4.

**Comment by nglasl** [comment] 2019-03-18 05:18
@tardinha sweet. It's hard to make the constraint any looser without just saying "give me **dev-master**", which is likely to cause issues at some point in the future. I'm happy for this to be bumped to either 3 or 4 given you've done the testing. If you throw a PR in I can make sure it's merged and tagged appropriately.

**Comment by tardinha** [comment] 2019-03-18 05:19
@nglasl, well, I don't wanna close out the older installs. how's about >=2.0?

**Comment by nglasl** [comment] 2019-03-18 05:23
@tardinha the problem is that can resolve to 5.0 which may introduce issues. The recommended versioning approach for libraries/modules is to use the caret operator (https://getcomposer.org/doc/articles/versions.md#caret-version-range-), but I understand they've been doing some major version bumps here that make the caret operator less than ideal. I'd be keen to hear thoughts from others, @stephenmcm or @JoshuaCarter care to weigh in?

Edit: maybe `>=2.0, <5.0`?

**Comment by JoshuaCarter** [comment] 2019-03-18 05:28
I'm generally for explicit requirements that make few assumptions/predictions, so if we know that `>=2.0, <5.0` is safe, that's good by me. Can confirm it's been working with `3`.

**Comment by tardinha** [comment] 2019-03-18 05:39
Yep, I dig. Happy with go with the flow on this.

**Comment by nglasl** [comment] 2019-03-19 01:13
PR merged, going to close this. Thanks again!

**Closed as completed by nglasl** 2019-03-19 01:13 UTC
Labels: affects/v4, effort/medium
